Importing PyTorch

In [1]:
import torch
torch.__version__

'2.2.0+cu121'

In [2]:
#Creating a scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Check number of dimensions
scalar.ndim

0

In [4]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
# Check number of dimensions
MATRIX.ndim

2

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [10]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [11]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [14]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7846, 0.7262, 0.7338, 0.3290],
        [0.4403, 0.4332, 0.8948, 0.1998],
        [0.2445, 0.1370, 0.3227, 0.4279]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [15]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [16]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [17]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [18]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [19]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [20]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

In [21]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [22]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [23]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [24]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [25]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 0 ns, sys: 1.24 ms, total: 1.24 ms
Wall time: 2.17 ms


tensor(14)

In [26]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 324 µs, sys: 113 µs, total: 437 µs
Wall time: 724 µs


tensor(14)

In [27]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [28]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [29]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])