Importing PyTorch

In [2]:
import torch
torch.__version__

'2.2.0+cu121'

In [3]:
#Creating a scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Check number of dimensions
scalar.ndim

0

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
# Check number of dimensions
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [12]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])