Importing PyTorch

In [22]:
import torch
torch.__version__

'2.2.0+cu121'

In [23]:
#Creating a scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [24]:
# Check number of dimensions
scalar.ndim

0

In [25]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [26]:
vector.ndim

1

In [27]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [28]:
# Check number of dimensions
MATRIX.ndim

2

In [29]:
MATRIX.shape

torch.Size([2, 2])

In [30]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [31]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [32]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [33]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [35]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3614, 0.9729, 0.3882, 0.0498],
        [0.6950, 0.3119, 0.0628, 0.1415],
        [0.7685, 0.4029, 0.5058, 0.0753]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [36]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [39]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [40]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [41]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])